import { dirname, join, relative } from "node:path";
import type { DiscoveredTransport, DiscoveryResult } from "./types.ts";

type ManifestShape = {
  meta: {
    builtAt: string;
    discoveryHash: string;
  };
  modules: Array<{ kind: string; name: string; filePath: string }>;
  infra: Array<{ filePath: string }>;
  transport: Array<{ key: string; filePath: string; source: string }>;
};

const GENERATED_HEADER = `/**\n * This file is auto-generated by Dispatchkit runtime codegen.\n * Do not edit this file manually.\n */\n/* eslint-disable */\n`;

const normalizeSeparators = (value: string) => value.replace(/\\/g, "/");

function toImportPath(fromFile: string, toFile: string): string {
  let specifier = normalizeSeparators(relative(dirname(fromFile), toFile));
  if (!specifier.startsWith(".")) {
    specifier = `./${specifier}`;
  }
  return specifier.replace(/\.d\.ts$|\.ts$/, "");
}

async function writeIfChanged(path: string, content: string): Promise<void> {
  const file = Bun.file(path);
  if (await file.exists()) {
    const existing = await file.text();
    if (existing === content) {
      return;
    }
  }

  await Bun.write(path, content);
}

type TreeNode = {
  methodKey?: string;
  children: Map<string, TreeNode>;
};

function buildTree(
  operations: DiscoveryResult["operations"],
  kind: "query" | "mutation" | "action",
): TreeNode {
  const root: TreeNode = { children: new Map() };

  for (const operation of operations.filter((item) => item.kind === kind)) {
    const methodKey = `${kind}:${operation.operationName}`;
    root.children.set(operation.operationName, {
      children: new Map(),
      methodKey,
    });

    if (operation.operationSegments.length <= 1) {
      continue;
    }

    let current = root;
    for (
      let index = 0;
      index < operation.operationSegments.length;
      index += 1
    ) {
      const segment = operation.operationSegments[index]!;
      const next = current.children.get(segment) ?? {
        children: new Map<string, TreeNode>(),
      };
      current.children.set(segment, next);
      current = next;

      if (index === operation.operationSegments.length - 1) {
        current.methodKey = methodKey;
      }
    }
  }

  return root;
}

function renderTree(
  node: TreeNode,
  methodsByName: Map<string, string>,
  indent = "  ",
): string[] {
  const lines: string[] = [];

  const keys = [...node.children.keys()].sort((left, right) =>
    left.localeCompare(right),
  );
  for (const key of keys) {
    const child = node.children.get(key)!;
    if (child.methodKey && child.children.size === 0) {
      lines.push(
        `${indent}${JSON.stringify(key)}: ${methodsByName.get(child.methodKey)!};`,
      );
      continue;
    }

    const nestedLines = renderTree(child, methodsByName, `${indent}  `);
    if (child.methodKey) {
      lines.push(
        `${indent}${JSON.stringify(key)}: ${methodsByName.get(child.methodKey)!} & {`,
      );
      lines.push(...nestedLines);
      lines.push(`${indent}};`);
    } else {
      lines.push(`${indent}${JSON.stringify(key)}: {`);
      lines.push(...nestedLines);
      lines.push(`${indent}};`);
    }
  }

  return lines;
}

function renderLayerType(options: {
  aliases: string[];
  typeName: string;
  inferTypeName: "InferInfraModule";
}): string {
  const { aliases, typeName, inferTypeName } = options;

  if (aliases.length === 0) {
    return `export type ${typeName} = Record<string, unknown>;`;
  }

  const unionMembers = aliases
    .map((alias) => `  | ${inferTypeName}<typeof ${alias}>`)
    .join("\n");

  return `type ${typeName}Union =\n${unionMembers};\n\nexport type ${typeName} = Simplify<UnionToIntersection<${typeName}Union>>;`;
}

function createTransportType(options: {
  aliases: Array<{ alias: string; key: string }>;
}): string {
  if (options.aliases.length === 0) {
    return "export type GeneratedTransport = Record<string, unknown>;";
  }

  const lines = options.aliases
    .sort((left, right) => left.key.localeCompare(right.key))
    .map(
      ({ alias, key }) =>
        `  ${JSON.stringify(key)}: InferTransportModule<typeof ${alias}>;`,
    );

  return `export interface GeneratedTransport {\n${lines.join("\n")}\n}`;
}

function createBusTypesContent(
  outputPath: string,
  srcDir: string,
  discovery: DiscoveryResult,
): string {
  const imports: string[] = [
    `import type { BusMethod, OperationInput, OperationReturn, InferInfraModule, InferTransportModule, Simplify, UnionToIntersection } from "@orria/dispatchkit";`,
  ];

  const methodTypes = new Map<string, string>();

  discovery.operations.forEach((operation, index) => {
    const alias = `Operation${index}`;
    imports.push(
      `import type ${alias} from "${toImportPath(outputPath, join(srcDir, "modules", operation.filePath))}";`,
    );
    methodTypes.set(
      `${operation.kind}:${operation.operationName}`,
      `BusMethod<OperationInput<typeof ${alias}>, OperationReturn<typeof ${alias}>>`,
    );
  });

  const infraAliases: string[] = [];
  discovery.infra.forEach((filePath, index) => {
    const alias = `Infra${index}`;
    infraAliases.push(alias);
    imports.push(
      `import type ${alias} from "${toImportPath(outputPath, join(srcDir, "infra", filePath))}";`,
    );
  });

  const transportAliases: Array<{ alias: string; key: string }> = [];
  discovery.transport.forEach((module, index) => {
    const alias = `Transport${index}`;
    transportAliases.push({ alias, key: module.key });
    const layerDir = module.source === "infra" ? "infra" : "transport";
    imports.push(
      `import type ${alias} from "${toImportPath(outputPath, join(srcDir, layerDir, module.filePath))}";`,
    );
  });

  const queryTree = buildTree(discovery.operations, "query");
  const mutationTree = buildTree(discovery.operations, "mutation");
  const actionTree = buildTree(discovery.operations, "action");

  const queryLines = renderTree(queryTree, methodTypes);
  const mutationLines = renderTree(mutationTree, methodTypes);
  const actionLines = renderTree(actionTree, methodTypes);

  const generatedInfraType = renderLayerType({
    aliases: infraAliases,
    typeName: "GeneratedInfra",
    inferTypeName: "InferInfraModule",
  });

  const generatedTransportType = createTransportType({
    aliases: transportAliases,
  });

  return `${GENERATED_HEADER}${imports.join("\n")}

export interface GeneratedQueryBus {
${queryLines.length > 0 ? queryLines.join("\n") : "  // no query operations discovered"}
}

export interface GeneratedMutationBus {
${mutationLines.length > 0 ? mutationLines.join("\n") : "  // no mutation operations discovered"}
}

export interface GeneratedActionBus {
${actionLines.length > 0 ? actionLines.join("\n") : "  // no action operations discovered"}
}

export interface GeneratedBus {
  query: GeneratedQueryBus;
  mutation: GeneratedMutationBus;
  action: GeneratedActionBus;
}

${generatedInfraType}

${generatedTransportType}
`;
}

function createRuntimeTypesContent(options: {
  outputPath: string;
  srcDir: string;
  discovery: DiscoveryResult;
}): string {
  const busImport = toImportPath(
    options.outputPath,
    join(dirname(options.outputPath), "bus.d.ts"),
  );

  const configImport = options.discovery.configPath
    ? `import type AppConfigDefinition from "${toImportPath(options.outputPath, join(options.srcDir, options.discovery.configPath))}";\n`
    : "";

  const configType = options.discovery.configPath
    ? "RuntimeDefaultConfig & InferConfigFromDefinition<typeof AppConfigDefinition>"
    : "RuntimeDefaultConfig";

  return `${GENERATED_HEADER}import type { GeneratedBus, GeneratedInfra, GeneratedTransport } from "${busImport}";
import type { InferConfigFromDefinition, LoggerLike, RuntimeDefaultConfig } from "@orria/dispatchkit";
${configImport}
export type GeneratedConfig = ${configType};

export interface RuntimeContext {
  config: GeneratedConfig;
  logger: LoggerLike;
  infra: GeneratedInfra;
  bus: GeneratedBus;
  transport: GeneratedTransport;
}

declare global {
  var runtime: RuntimeContext;
}

export {};
`;
}

function createGeneratedIndex(): string {
  return `${GENERATED_HEADER}export type {
  GeneratedActionBus,
  GeneratedBus,
  GeneratedInfra,
  GeneratedMutationBus,
  GeneratedQueryBus,
  GeneratedTransport,
} from "./bus";
export type { GeneratedConfig, RuntimeContext } from "./runtime";
`;
}

function createManifest(
  discovery: DiscoveryResult,
  discoveryHash: string,
): ManifestShape {
  return {
    meta: {
      builtAt: new Date().toISOString(),
      discoveryHash,
    },
    modules: discovery.operations.map((operation) => ({
      kind: operation.kind,
      name: operation.operationName,
      filePath: operation.filePath,
    })),
    infra: discovery.infra.map((filePath) => ({ filePath })),
    transport: discovery.transport.map((module) => ({
      key: module.key,
      filePath: module.filePath,
      source: module.source,
    })),
  };
}

function getManifestDiscoveryPayload(discovery: DiscoveryResult): {
  modules: Array<{ kind: string; name: string; filePath: string }>;
  infra: Array<{ filePath: string }>;
  transport: Array<{ key: string; filePath: string; source: string }>;
} {
  return {
    modules: discovery.operations
      .map((operation) => ({
        kind: operation.kind,
        name: operation.operationName,
        filePath: operation.filePath,
      }))
      .sort(
        (left, right) =>
          left.kind.localeCompare(right.kind) ||
          left.name.localeCompare(right.name) ||
          left.filePath.localeCompare(right.filePath),
      ),
    infra: discovery.infra
      .map((filePath) => ({ filePath }))
      .sort((left, right) => left.filePath.localeCompare(right.filePath)),
    transport: discovery.transport
      .map((module) => ({
        key: module.key,
        filePath: module.filePath,
        source: module.source,
      }))
      .sort(
        (left, right) =>
          left.key.localeCompare(right.key) ||
          left.source.localeCompare(right.source) ||
          left.filePath.localeCompare(right.filePath),
      ),
  };
}

function hashDiscovery(discovery: DiscoveryResult): string {
  const payload = getManifestDiscoveryPayload(discovery);
  const serialized = JSON.stringify(payload);
  const hasher = new Bun.CryptoHasher("sha256");
  hasher.update(serialized);
  return hasher.digest("hex");
}

async function shouldRewriteManifest(
  manifestPath: string,
  nextDiscoveryHash: string,
): Promise<boolean> {
  const file = Bun.file(manifestPath);
  if (!(await file.exists())) {
    return true;
  }

  try {
    const parsed = (await file.json()) as {
      meta?: { discoveryHash?: unknown };
    };
    const currentHash = parsed?.meta?.discoveryHash;
    return typeof currentHash !== "string" || currentHash !== nextDiscoveryHash;
  } catch {
    return true;
  }
}

export async function generateArtifacts(options: {
  srcDir: string;
  generatedDir: string;
  discovery: DiscoveryResult;
}): Promise<void> {
  await Bun.write(join(options.generatedDir, ".keep"), "");

  const busPath = join(options.generatedDir, "bus.d.ts");
  const runtimePath = join(options.generatedDir, "runtime.d.ts");
  const indexPath = join(options.generatedDir, "index.ts");
  const manifestPath = join(options.generatedDir, "manifest.json");

  const busContent = createBusTypesContent(
    busPath,
    options.srcDir,
    options.discovery,
  );
  const runtimeContent = createRuntimeTypesContent({
    outputPath: runtimePath,
    srcDir: options.srcDir,
    discovery: options.discovery,
  });
  const indexContent = createGeneratedIndex();

  const discoveryHash = hashDiscovery(options.discovery);
  if (await shouldRewriteManifest(manifestPath, discoveryHash)) {
    const manifest = createManifest(options.discovery, discoveryHash);
    const manifestContent = `${JSON.stringify(manifest, null, 2)}\n`;
    await Bun.write(manifestPath, manifestContent);
  }
  await writeIfChanged(busPath, busContent);
  await writeIfChanged(runtimePath, runtimeContent);
  await writeIfChanged(indexPath, indexContent);
}
